# Generated by Django 6.0.6 on 2026-06-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='giftmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
